name: Pre-build checks
run-name: Preparing for deploy to GH Pages
on: [push, pull_request]
permissions:
  contents: write
  id-token: write 
  pages: write

jobs:
  Code-Check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      
      - name: Install dependencies
        run: npm install -D tailwindcss eslint
      
      - name: Minify Tailwind CSS
        run: npx tailwindcss -i ./static/css/input.css -o ./static/css/index.css --minify

      - name: Install dependencies
        run: npm install eslint --save-dev
      
      - name: Lint Javascript
        run: npx eslint ./static/js/switchControl.js --no-config-lookup
  
        continue-on-error: true

      - name: Prepare artifact for upload
        run: |
          mkdir -p artifact
          cp -r ./static ./artifact/
          cp -r ./index.html ./artifact/
    
      - name: Upload page artifact
        uses: actions/upload-pages-artifact@v1
        with:
          name: personal-website
          path: artifact/

  Deploy:
    needs: Code-Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
    
      - name: Deploy to Github Pages
        uses: actions/deploy-pages@v1
        with:
          artifact_name: personal-website
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  Verify:
    runs-on: ubuntu-latest
    needs: Deploy
    steps:
      - name: Verify deployment
        run: |
          echo "Verifying deployment"
          for i in {1..5}; do
            curl -I https://fer-hnndz.github.io/ | grep "200 OK" && break || sleep 10
          done

        
