name: Minify Tailwind CSS
run-name: Minifying Tailwind
on: push
permissions:
    contents: write

jobs:
  Minify-Tailwind:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      
      - name: Install dependencies
        run: npm install -D tailwindcss
        
      - name: Minify Tailwind CSS
        run: npx tailwindcss -i ./static/css/input.css -o ./static/css/index.css --minify

      - name: Commit and push minified CSS
        run: |
          git config --global user.name "fer-hnndz"
          git config --global user.email "jfernandohernandez28@gmail.com"
          git add ./static/css/index.css
          git commit -m "Minified tailwind"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
