name: Pre-build checks
run-name: Preparing for deploy to GH Pages
on: [push, pull_request] 
permissions:
    contents: write

jobs:
  Minify-Tailwind:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      
      - name: Install dependencies
        run: |
          npm install -D tailwindcss
          npm install -D eslint
        
      - name: Minify Tailwind CSS
        run: npx tailwindcss -i ./static/css/input.css -o ./static/css/index.css --minify

      - name: Commit and push minified CSS
        run: |
          git config --global user.name "fer-hnndz"
          git config --global user.email "jfernandohernandez28@gmail.com"
          git add ./static/css/index.css
          git commit -m "Minified tailwind"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Lint Javascript
        run: npx eslint ./static/js/switchControl.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload page artifact
        uses: actions/upload-pages-artifact@v1
        with:
          name: personal-website
          path: /

      - name: Deploy to Github Pages
        uses: actions/deploy-pages@v1
        with:
          artifact_name: personal-website